-- ============================================================================
--  01_schema.sql  —  Schemat logiczny i fizyczny (DDL)
-- ----------------------------------------------------------------------------
--  Platforma aukcyjna produktów elektronicznych.
--  Model w 3. postaci normalnej (3NF): każdy atrybut niekluczowy zależy
--  wyłącznie od klucza głównego; brak zależności przechodnich (atrybuty
--  słownikowe — producent, kategoria, metoda płatności — wydzielone do
--  osobnych tabel).
--
--  Konwencje:
--    * klucze główne: kolumna `id` typu GENERATED BY DEFAULT AS IDENTITY,
--    * znaczniki czasu: TIMESTAMPTZ (świadomość strefy czasowej),
--    * kwoty pieniężne: NUMERIC(12,2) (brak błędów zaokrągleń typów float),
--    * statusy: typy wyliczeniowe ENUM (czytelność + integralność dziedziny).
-- ============================================================================

-- ----------------------------------------------------------------------------
--  Typy wyliczeniowe (ENUM) — ograniczają dziedzinę kolumn statusowych.
-- ----------------------------------------------------------------------------
CREATE TYPE typ_adresu        AS ENUM ('rozliczeniowy', 'dostawy');
CREATE TYPE stan_produktu     AS ENUM ('nowy', 'uzywany', 'odnowiony');
CREATE TYPE status_aukcji     AS ENUM ('aktywna', 'zakonczona', 'anulowana');
CREATE TYPE status_platnosci  AS ENUM ('oczekujaca', 'oplacona', 'anulowana');

-- ----------------------------------------------------------------------------
--  Domena pomocnicza — kwota dodatnia (współdzielone ograniczenie CHECK).
-- ----------------------------------------------------------------------------
CREATE DOMAIN kwota_dodatnia AS NUMERIC(12,2)
    CHECK (VALUE > 0);

-- ============================================================================
--  TABELA: uzytkownicy
--  Konta na platformie. `haslo_hash` przechowuje wyłącznie skrót bcrypt
--  (patrz 07_role_uprawnienia.sql / pgcrypto) — nigdy hasła jawnego.
-- ============================================================================
CREATE TABLE uzytkownicy (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_uzytkownika VARCHAR(50)  NOT NULL UNIQUE,
    email             VARCHAR(255) NOT NULL UNIQUE,
    haslo_hash        TEXT         NOT NULL,
    imie              VARCHAR(100),
    nazwisko          VARCHAR(100),
    telefon           VARCHAR(20),
    data_rejestracji  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    aktywny           BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Prosta walidacja formatu adresu e-mail.
    CONSTRAINT chk_uzytkownicy_email
        CHECK (email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')
);
COMMENT ON TABLE  uzytkownicy IS 'Konta użytkowników platformy aukcyjnej';
COMMENT ON COLUMN uzytkownicy.haslo_hash IS 'Skrót bcrypt hasła (pgcrypto), nigdy hasło jawne';

-- ============================================================================
--  TABELA: adresy
--  Adresy użytkownika (rozliczeniowy / dostawy). Relacja 1:N do uzytkownicy.
-- ============================================================================
CREATE TABLE adresy (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uzytkownik_id BIGINT      NOT NULL
                  REFERENCES uzytkownicy(id) ON DELETE CASCADE,
    ulica         VARCHAR(150) NOT NULL,
    miasto        VARCHAR(100) NOT NULL,
    kod_pocztowy  VARCHAR(12)  NOT NULL,
    kraj          VARCHAR(60)  NOT NULL DEFAULT 'Polska',
    typ           typ_adresu   NOT NULL
);
COMMENT ON TABLE adresy IS 'Adresy rozliczeniowe i dostawy użytkowników';

-- ============================================================================
--  TABELA: kategorie
--  Hierarchia kategorii (Elektronika -> Laptopy / Smartfony / ...).
--  Samoodwołanie FK umożliwia rekurencyjne CTE po drzewie kategorii.
-- ============================================================================
CREATE TABLE kategorie (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa                  VARCHAR(100) NOT NULL UNIQUE,
    kategoria_nadrzedna_id BIGINT
                           REFERENCES kategorie(id) ON DELETE SET NULL,
    -- Kategoria nie może być własnym rodzicem.
    CONSTRAINT chk_kategorie_nie_samo
        CHECK (kategoria_nadrzedna_id IS NULL OR kategoria_nadrzedna_id <> id)
);
COMMENT ON TABLE kategorie IS 'Hierarchiczny słownik kategorii produktów';

-- ============================================================================
--  TABELA: producenci
--  Wydzielona, aby uniknąć zależności przechodniej w `produkty`
--  (nazwa producenta -> kraj producenta zależy od producenta, nie produktu).
-- ============================================================================
CREATE TABLE producenci (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa VARCHAR(100) NOT NULL UNIQUE,
    kraj  VARCHAR(60)
);
COMMENT ON TABLE producenci IS 'Słownik producentów sprzętu elektronicznego';

-- ============================================================================
--  TABELA: produkty
--  Opis przedmiotu wystawianego na aukcji.
-- ============================================================================
CREATE TABLE produkty (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa        VARCHAR(200)  NOT NULL,
    opis         TEXT,
    kategoria_id BIGINT        NOT NULL
                 REFERENCES kategorie(id)  ON DELETE RESTRICT,
    producent_id BIGINT        NOT NULL
                 REFERENCES producenci(id) ON DELETE RESTRICT,
    stan         stan_produktu NOT NULL
);
COMMENT ON TABLE produkty IS 'Produkty elektroniczne będące przedmiotem aukcji';

-- ============================================================================
--  TABELA: aukcje
--  Aukcja jednego produktu wystawiona przez sprzedającego.
--  `cena_aktualna` to KONTROLOWANA REDUNDANCJA utrzymywana triggerem
--  (trg_aktualizuj_cene) — przyspiesza odczyt, świadomie udokumentowana.
-- ============================================================================
CREATE TABLE aukcje (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produkt_id       BIGINT         NOT NULL
                     REFERENCES produkty(id)    ON DELETE RESTRICT,
    sprzedajacy_id   BIGINT         NOT NULL
                     REFERENCES uzytkownicy(id) ON DELETE RESTRICT,
    cena_wywolawcza  kwota_dodatnia NOT NULL,
    cena_minimalna   kwota_dodatnia,                 -- cena rezerwowa (reserve), opcjonalna
    cena_aktualna    kwota_dodatnia NOT NULL,        -- redundancja kontrolowana (trigger)
    krok_przebicia   kwota_dodatnia NOT NULL DEFAULT 1.00,
    data_rozpoczecia TIMESTAMPTZ    NOT NULL DEFAULT now(),
    data_zakonczenia TIMESTAMPTZ    NOT NULL,
    status           status_aukcji  NOT NULL DEFAULT 'aktywna',
    zwyciezca_id     BIGINT
                     REFERENCES uzytkownicy(id) ON DELETE SET NULL,
    CONSTRAINT chk_aukcje_daty
        CHECK (data_zakonczenia > data_rozpoczecia),
    -- Cena rezerwowa nie może być niższa niż wywoławcza.
    CONSTRAINT chk_aukcje_rezerwa
        CHECK (cena_minimalna IS NULL OR cena_minimalna >= cena_wywolawcza),
    -- Cena bieżąca nigdy poniżej wywoławczej (start = wywoławcza, oferty tylko podbijają).
    CONSTRAINT chk_aukcje_cena_aktualna
        CHECK (cena_aktualna >= cena_wywolawcza),
    -- Zwycięzca może istnieć tylko dla aukcji zakończonej.
    CONSTRAINT chk_aukcje_zwyciezca
        CHECK (zwyciezca_id IS NULL OR status = 'zakonczona')
);
COMMENT ON TABLE  aukcje IS 'Aukcje produktów; status: aktywna/zakonczona/anulowana';
COMMENT ON COLUMN aukcje.cena_aktualna IS 'Redundancja kontrolowana utrzymywana triggerem trg_aktualizuj_cene';

-- ============================================================================
--  TABELA: oferty
--  Pojedyncza oferta (bid) złożona w aukcji.
-- ============================================================================
CREATE TABLE oferty (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aukcja_id    BIGINT         NOT NULL
                 REFERENCES aukcje(id)      ON DELETE CASCADE,
    kupujacy_id  BIGINT         NOT NULL
                 REFERENCES uzytkownicy(id) ON DELETE RESTRICT,
    kwota        kwota_dodatnia NOT NULL,
    data_zlozenia TIMESTAMPTZ   NOT NULL DEFAULT now()
);
COMMENT ON TABLE oferty IS 'Oferty (licytacje) składane w aukcjach';

-- ============================================================================
--  TABELA: metody_platnosci
--  Słownik metod płatności (przelew, BLIK, karta, ...).
-- ============================================================================
CREATE TABLE metody_platnosci (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa VARCHAR(60) NOT NULL UNIQUE
);
COMMENT ON TABLE metody_platnosci IS 'Słownik dostępnych metod płatności';

-- ============================================================================
--  TABELA: transakcje
--  Rozliczenie zakończonej aukcji. Relacja 1:1 z aukcją (UNIQUE aukcja_id).
-- ============================================================================
CREATE TABLE transakcje (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aukcja_id           BIGINT         NOT NULL UNIQUE
                        REFERENCES aukcje(id)           ON DELETE RESTRICT,
    kupujacy_id         BIGINT         NOT NULL
                        REFERENCES uzytkownicy(id)      ON DELETE RESTRICT,
    sprzedajacy_id      BIGINT         NOT NULL
                        REFERENCES uzytkownicy(id)      ON DELETE RESTRICT,
    kwota               kwota_dodatnia NOT NULL,
    metoda_platnosci_id BIGINT         NOT NULL
                        REFERENCES metody_platnosci(id) ON DELETE RESTRICT,
    status_platnosci    status_platnosci NOT NULL DEFAULT 'oczekujaca',
    data                TIMESTAMPTZ    NOT NULL DEFAULT now(),
    -- Kupujący nie może być sprzedającym w tej samej transakcji.
    CONSTRAINT chk_transakcje_strony
        CHECK (kupujacy_id <> sprzedajacy_id)
);
COMMENT ON TABLE transakcje IS 'Rozliczenia zakończonych aukcji (1:1 z aukcją)';

-- ============================================================================
--  TABELA: recenzje
--  Wzajemne oceny stron transakcji (1..5).
-- ============================================================================
CREATE TABLE recenzje (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transakcja_id BIGINT   NOT NULL
                  REFERENCES transakcje(id)  ON DELETE CASCADE,
    autor_id      BIGINT   NOT NULL
                  REFERENCES uzytkownicy(id) ON DELETE RESTRICT,
    oceniany_id   BIGINT   NOT NULL
                  REFERENCES uzytkownicy(id) ON DELETE RESTRICT,
    ocena         SMALLINT NOT NULL,
    komentarz     TEXT,
    data          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_recenzje_ocena   CHECK (ocena BETWEEN 1 AND 5),
    CONSTRAINT chk_recenzje_strony  CHECK (autor_id <> oceniany_id),
    -- Jeden autor może wystawić tylko jedną recenzję na transakcję.
    CONSTRAINT uq_recenzje_autor    UNIQUE (transakcja_id, autor_id)
);
COMMENT ON TABLE recenzje IS 'Oceny (1..5) wystawiane wzajemnie przez strony transakcji';

-- ============================================================================
--  TABELA: obserwowane
--  Lista obserwowanych aukcji. Klucz złożony (uzytkownik_id, aukcja_id).
-- ============================================================================
CREATE TABLE obserwowane (
    uzytkownik_id BIGINT NOT NULL
                  REFERENCES uzytkownicy(id) ON DELETE CASCADE,
    aukcja_id     BIGINT NOT NULL
                  REFERENCES aukcje(id)      ON DELETE CASCADE,
    data          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (uzytkownik_id, aukcja_id)
);
COMMENT ON TABLE obserwowane IS 'Aukcje obserwowane przez użytkowników (relacja M:N)';

-- ============================================================================
--  TABELA: dziennik_zmian
--  Tabela audytowa wypełniana triggerem trg_audyt na kluczowych tabelach.
-- ============================================================================
CREATE TABLE dziennik_zmian (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela        TEXT        NOT NULL,
    operacja      TEXT        NOT NULL CHECK (operacja IN ('INSERT','UPDATE','DELETE')),
    id_rekordu    TEXT,
    dane          JSONB,
    uzytkownik_db TEXT        NOT NULL DEFAULT current_user,
    czas          TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE dziennik_zmian IS 'Dziennik audytowy zmian (wypełniany triggerem trg_audyt)';
